CXX           = g++
COMPILE_FLAGS = -std=c++11 -Wall -Wextra -g
CXXFLAGS      = $(COMPILE_FLAGS)
LIBS          = 
DEL_FILE      = rm -f

OBJECTS_1_SAVINGS				= 	1-savings.o
OBJECTS_2_GOLOSA				= 	2-golosa.o
OBJECTS_3_SWEEP_ALGORITHM		= 	3-sweep-algorithm.o
OBJECTS_4_OTRA_CLUSTERIZACION	= 	4-otra-clusterizacion.o
OBJECTS_5_SIMULATED_ANNEALING	= 	5-simulated-annealing.o

TARGET_1_SAVINGS				= 	1-savings
TARGET_2_GOLOSA					= 	2-golosa
TARGET_3_SWEEP_ALGORITHM		= 	3-sweep-algorithm
TARGET_4_OTRA_CLUSTERIZACION	= 	4-otra-clusterizacion
TARGET_5_SIMULATED_ANNEALING	= 	5-simulated-annealing

all: $(TARGET_1_SAVINGS) $(TARGET_2_GOLOSA) $(TARGET_3_SWEEP_ALGORITHM) $(TARGET_4_OTRA_CLUSTERIZACION) $(TARGET_5_SIMULATED_ANNEALING)

$(TARGET_1_SAVINGS):  $(OBJECTS_1_SAVINGS)  
	$(CXX) -o $(TARGET_1_SAVINGS) $(OBJECTS_1_SAVINGS) $(OBJCOMP) $(LIBS)

$(TARGET_2_GOLOSA):  $(OBJECTS_2_GOLOSA)  
	$(CXX) -o $(TARGET_2_GOLOSA) $(OBJECTS_2_GOLOSA) $(OBJCOMP) $(LIBS)

$(TARGET_3_SWEEP_ALGORITHM):  $(OBJECTS_3_SWEEP_ALGORITHM)  
	$(CXX) -o $(TARGET_3_SWEEP_ALGORITHM) $(OBJECTS_3_SWEEP_ALGORITHM) $(OBJCOMP) $(LIBS)


$(TARGET_4_OTRA_CLUSTERIZACION):  $(OBJECTS_4_OTRA_CLUSTERIZACION)  
	$(CXX) -o $(TARGET_4_OTRA_CLUSTERIZACION) $(OBJECTS_4_OTRA_CLUSTERIZACION) $(OBJCOMP) $(LIBS)

$(TARGET_5_SIMULATED_ANNEALING):  $(OBJECTS_5_SIMULATED_ANNEALING)  
	$(CXX) -o $(TARGET_5_SIMULATED_ANNEALING) $(OBJECTS_5_SIMULATED_ANNEALING) $(OBJCOMP) $(LIBS)

clean: 
	-$(DEL_FILE) $(OBJECTS_1_SAVINGS)
	-$(DEL_FILE) $(OBJECTS_2_GOLOSA)
	-$(DEL_FILE) $(OBJECTS_3_SWEEP_ALGORITHM)
	-$(DEL_FILE) $(OBJECTS_4_OTRA_CLUSTERIZACION)
	-$(DEL_FILE) $(OBJECTS_5_SIMULATED_ANNEALING)
	-$(DEL_FILE) *~ core *.core
	-$(DEL_FILE) $(TARGET_1_SAVINGS)
	-$(DEL_FILE) $(TARGET_2_GOLOSA)
	-$(DEL_FILE) $(TARGET_3_SWEEP_ALGORITHM)
	-$(DEL_FILE) $(TARGET_4_OTRA_CLUSTERIZACION)
	-$(DEL_FILE) $(TARGET_5_SIMULATED_ANNEALING)


$(TARGET_1_SAVINGS).o: src/$(TARGET_1_SAVINGS).cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(TARGET_1_SAVINGS).o src/$(TARGET_1_SAVINGS).cpp

$(TARGET_2_GOLOSA).o: src/$(TARGET_2_GOLOSA).cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(TARGET_2_GOLOSA).o src/$(TARGET_2_GOLOSA).cpp

$(TARGET_3_SWEEP_ALGORITHM).o: src/$(TARGET_3_SWEEP_ALGORITHM).cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(TARGET_3_SWEEP_ALGORITHM).o src/$(TARGET_3_SWEEP_ALGORITHM).cpp


$(TARGET_4_OTRA_CLUSTERIZACION).o: src/$(TARGET_4_OTRA_CLUSTERIZACION).cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(TARGET_4_OTRA_CLUSTERIZACION).o src/$(TARGET_4_OTRA_CLUSTERIZACION).cpp

$(TARGET_5_SIMULATED_ANNEALING).o: src/$(TARGET_5_SIMULATED_ANNEALING).cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(TARGET_5_SIMULATED_ANNEALING).o src/$(TARGET_5_SIMULATED_ANNEALING).cpp

aux.o: src/aux.cpp src/include/aux.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aux.o src/aux.cpp